"""created Scenarios table

Revision ID: 8f2abe3a6d95
Revises: 0b1885a08f9d
Create Date: 2026-04-19 16:36:00.918844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f2abe3a6d95'
down_revision: Union[str, Sequence[str], None] = '0b1885a08f9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenarios',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_scenarios_user_id'), 'scenarios', ['user_id'], unique=False)
    op.add_column('sources', sa.Column('scenario_id', sa.Integer(), nullable=False))
    op.alter_column('sources', 'coordinates',
                    existing_type=postgresql.JSON(astext_type=sa.Text()),
                    nullable=True)
    op.create_index(op.f('ix_sources_scenario_id'), 'sources', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_sources_substance_id'), 'sources', ['substance_id'], unique=False)
    op.create_foreign_key(None, 'sources', 'scenarios', ['scenario_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sources', type_='foreignkey')
    op.drop_index(op.f('ix_sources_substance_id'), table_name='sources')
    op.drop_index(op.f('ix_sources_scenario_id'), table_name='sources')
    op.alter_column('sources', 'coordinates',
                    existing_type=postgresql.JSON(astext_type=sa.Text()),
                    nullable=False)
    op.drop_column('sources', 'scenario_id')
    op.drop_index(op.f('ix_scenarios_user_id'), table_name='scenarios')
    op.drop_index(op.f('ix_scenarios_id'), table_name='scenarios')
    op.drop_table('scenarios')
    # ### end Alembic commands ###
